name: Deploy TigerOne to DigitalOcean VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "=== 0. Configurando fuso horário do servidor para São Paulo ==="
          sudo timedatectl set-timezone America/Sao_Paulo
          timedatectl > /root/TigerOne/frontend/timezone.txt
          /root/TigerOne/venv/bin/python -c "import time, datetime; print('time.tzname:', time.tzname); print('datetime.now():', datetime.datetime.now())" > /root/TigerOne/frontend/pytime.txt
          env > /root/TigerOne/frontend/env.txt
          ls -la /etc/localtime > /root/TigerOne/frontend/tz_link.txt

          echo "=== 1. Entrando na pasta e puxando o código novo ==="
          cd /root/TigerOne
          git pull origin main

          echo "=== 2. Atualizando dependências no ambiente virtual ==="
          ./venv/bin/pip install -r requirements.txt

          echo "=== 3. Reiniciando o serviço do TigerOne ==="
          sudo systemctl restart tigerone

          echo "=== Deploy finalizado com sucesso! ==="
